import mongoose from 'mongoose';

const incidentSchema = new mongoose.Schema(
  {
    // Night and timing
    nightDate: {
      type: Date,
      required: true,
      index: true,
      description: 'Date only (no time) — which night this incident occurred',
    },

    // Identification and description
    title: {
      type: String,
      required: true,
      description: 'Human-readable title (auto-generated by correlation service)',
    },

    // Events grouped into this incident
    eventIds: {
      type: [mongoose.Schema.Types.ObjectId],
      ref: 'Event',
      required: true,
      description: 'All events correlated into this incident',
    },

    // Primary location where incident occurred
    primaryLocation: {
      name: {
        type: String,
        required: true,
      },
      coordinates: {
        lat: {
          type: Number,
          required: true,
        },
        lng: {
          type: Number,
          required: true,
        },
      },
      zone: {
        type: String,
        enum: ['perimeter', 'yard', 'block', 'access_point', 'road'],
        required: true,
      },
    },

    // How events were grouped
    correlationType: {
      type: String,
      enum: ['spatial', 'temporal', 'entity', 'cross_type'],
      required: true,
      description:
        'spatial: same location | temporal: time proximity | entity: same vehicle/person | cross_type: different event types at same place',
    },

    // Entity if applicable
    entityInvolved: {
      type: {
        type: String,
        enum: ['vehicle', 'employee', 'unknown'],
      },
      id: String,
      displayName: String,
    },

    // Status and priority
    status: {
      type: String,
      enum: ['pending', 'investigating', 'complete', 'needs_followup'],
      default: 'pending',
      index: true,
    },

    priority: {
      type: Number,
      min: 1,
      max: 5,
      required: true,
      index: true,
      description: 'Priority score 1 (highest) to 5 (lowest), set by planner',
    },

    // Investigation link
    investigationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Investigation',
      nullable: true,
      description: 'Set after AI agent begins/completes investigation',
    },

    // AI agent findings
    agentSummary: {
      type: String,
      description: 'One-paragraph plain English summary from AI agent',
    },

    finalSeverity: {
      type: String,
      enum: ['harmless', 'monitor', 'escalate', 'uncertain'],
      index: true,
      description: 'Final severity assessment after investigation',
    },

    // Special flags
    raghavsNote: {
      type: Boolean,
      default: false,
      description: "Flag for Raghav's Block C concern or other supervisor priority",
    },

    // Legacy fields (for compatibility)
    incidentId: String,
    severity: String,
    description: String,
    assignedTo: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    tags: [String],
  },
  {
    timestamps: true,
  }
);

// Indexes for common queries
incidentSchema.index({ nightDate: 1, status: 1 });
incidentSchema.index({ priority: 1, nightDate: -1 });
incidentSchema.index({ finalSeverity: 1, nightDate: -1 });
incidentSchema.index({ raghavsNote: 1});

// Ensure virtuals are included in JSON output
incidentSchema.set('toJSON', { virtuals: true });

export default mongoose.model('Incident', incidentSchema);
